services:
  - type: web
    name: rays-backend
    env: node
    plan: free
    branch: main
    buildCommand: |
      apt-get update && apt-get install -y php-cli php-mbstring php-xml composer
      composer install --no-dev --optimize-autoloader
    startCommand: php -S 0.0.0.0:10000 -t public
    envVars:
      - key: APP_KEY
        sync: false
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: OPENWEATHER_API_KEY
        sync: false
