services:
  - type: web
    name: rays-backend
    env: docker
    dockerfilePath: Dockerfile
    buildCommand: |
      # You may specify custom build steps if needed, like setting up the database
      echo "No build command needed for backend"
    startCommand: php artisan serve --host=0.0.0.0 --port=80
    envVars:
      - key: APP_KEY
        sync: true
      - key: DB_CONNECTION
        sync: true
      # Add other environment variables for your database and app config here
      - key: DB_HOST
        sync: true
      - key: DB_PORT
        sync: true
      - key: DB_DATABASE
        sync: true
      - key: DB_USERNAME
        sync: true
      - key: DB_PASSWORD
        sync: true